# Generated by Django 4.1.3 on 2022-11-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
                'unique_together': {('nombre',)},
            },
        ),
    ]
