# Generated by Django 4.1.3 on 2022-11-08 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siscapru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True)),
                ('precondicion', models.TextField(blank=True, max_length=250, null=True)),
                ('pasos', models.TextField(blank=True, max_length=250, null=True)),
                ('resultado_esperado', models.TextField(blank=True, max_length=250, null=True)),
                ('postcondicion', models.TextField(blank=True, max_length=250, null=True)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('tipo', models.CharField(choices=[('F', 'Funcional'), ('N', 'No Funcional'), ('E', 'Estructural'), ('R', 'Regresión')], default='F', max_length=1)),
                ('variedad', models.CharField(choices=[('+', 'Positiva'), ('-', 'Negativa')], default='+', max_length=1)),
                ('prioridad', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='B', max_length=1)),
                ('evaluacion', models.CharField(choices=[('M', 'Manual'), ('A', 'Automática')], default='M', max_length=1)),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('L', 'Bloqueada'), ('A', 'Aprobada'), ('F', 'Fallo')], default='B', max_length=1)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_prueba', to='siscapru.proyecto')),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.AddConstraint(
            model_name='casoprueba',
            constraint=models.UniqueConstraint(fields=('codigo', 'proyecto'), name='caso_prueba_codigo_proyecto_unique'),
        ),
    ]
