# Generated by Django 4.1.3 on 2022-11-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscapru', '0002_casoprueba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoprueba',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='casoprueba',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='casoprueba',
            name='observacion',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='casoprueba',
            name='postcondicion',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Postcondición'),
        ),
        migrations.AlterField(
            model_name='casoprueba',
            name='precondicion',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Precondición'),
        ),
    ]
