# Generated by Django 4.1.3 on 2022-11-08 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siscapru', '0004_cicloprueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('L', 'Bloqueada'), ('A', 'Aprobada'), ('F', 'Fallo')], default='B', max_length=1)),
                ('comentario', models.TextField(blank=True, max_length=250, null=True)),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='evidencia/%Y/%m/%d/')),
                ('caso_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_ejecutadas', to='siscapru.casoprueba')),
                ('ciclo_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_ejecutadas', to='siscapru.cicloprueba')),
            ],
        ),
    ]
