# Generated by Django 4.1.3 on 2022-11-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscapru', '0005_ejecucionprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicloprueba',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
