# Generated by Django 4.1.3 on 2022-11-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscapru', '0006_alter_cicloprueba_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casoprueba',
            name='observacion',
        ),
        migrations.AddField(
            model_name='ejecucionprueba',
            name='regresion',
            field=models.BooleanField(default=False, verbose_name='¿Regresión?'),
        ),
        migrations.AlterField(
            model_name='casoprueba',
            name='tipo',
            field=models.CharField(choices=[('F', 'Funcional'), ('N', 'No Funcional'), ('E', 'Estructural')], default='F', max_length=1),
        ),
    ]
