# Generated by Django 4.1.3 on 2022-11-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siscapru', '0007_remove_casoprueba_observacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casoprueba',
            name='nombre',
        ),
    ]
