# Generated by Django 4.1.3 on 2022-11-18 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siscapru', '0008_ejecucionprueba_proyecto'),
        ('siscapru', '0008_remove_casoprueba_nombre'),
    ]

    operations = [
    ]
