# Generated by Django 4.1.3 on 2022-11-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siscapru', '0009_merge_20221118_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecucionprueba',
            name='proyecto',
        ),
    ]
